### ISSUE TITLE
Any way to calculate --smooth-corners property value to pixels?

### ISSUE THREAD

**Issue by venkatasrikanthkarri** [wopian/smooth-corners#11]
What value should i give to the `--smooth-corners` to get `4px` `border-radius`, Is there any formula to calculate this?

**Comment by wopian** [comment]
Values between `40` and `46` is roughly equivalent to 4px. I'm not sure how the [superellipse equation](https://en.wikipedia.org/wiki/Superellipse) can be mapped to pixel values however.
