### ISSUE TITLE
not supported in linux

### ISSUE THREAD

**Issue by UndeadMe** [wopian/smooth-corners#190]
hello dear. 
i am so glad someone created this special package for react and i was using this and when i switch into linux i realized its not working though

**Comment by wopian** [comment]
Can you add more details on this? Operating systems shouldn't have any impact on the functionality of this library - only browser support.

You can check current browser support here: https://developer.mozilla.org/en-US/docs/Web/API/CSS_Painting_API

**Comment by UndeadMe** [comment]
yup u r right !
actually its better to say its not working in the firefox
do u know any other way for implementing this feature in firefox? in fact i want to show the interface in all the browsers same

**Comment by wopian** [comment]
The best way to replicate it in Firefox that would be cross-browser is to use a hand-crafter clip-path that masks out the area desired - but this would need to be done for each aspect ratio you need (e.g 1x1 icon, 16x9 thumbnail).

This site will generate a superellipse SVG path for use with CSS clip-path: https://superellipse.xxhax.com/

**Comment by UndeadMe** [comment]
thanks a lot
