### ISSUE TITLE
Question for the border?

### ISSUE THREAD

**Issue by Uranbold** [wopian/smooth-corners#2]
How do we apply it on Borders, not an image and background?

**Comment by wopian** [comment]
CSS borders are unfortunately not supported as they do not work with `mask-image`.

```css
.box {
  border: red solid 1rem;
  mask-image: paint(smooth-corners);
```

![image](https://user-images.githubusercontent.com/3440094/114590034-2a0a5800-9c80-11eb-83c7-0dd73d68a8ea.png)

However, you could make a slightly bigger element using `::before` pseudo-element that would imitate a border.

Borders could also be implemented by extending the [paint worklet](https://github.com/wopian/smooth-corners/blob/master/paint.js) using the [Houdini Paint API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Painting_API/Guide)

**Comment by materia-admin** [comment]
👋 Same question about shadows

**Comment by bakharew** [comment]
👋 Same question about shadows

**Comment by wopian** [comment]
> 👋 Same question about shadows

Check out https://github.com/jwoo0122/awesome-smooth-corners for a fork that extended this worklet with shadows

**Comment by wopian** [comment]
@bakharew you can use it with JSDelivr 👍

https://cdn.jsdelivr.net/gh/jwoo0122/awesome-smooth-corners/paint.js
